#!/usr/bin/env python3
"""Generates the 1-bit digit faces for the Clock sleep screen.

Renders 0-9, ':' and '-' from each source font at the largest pixel size where
the widest possible face ("00:00" in the widest digits) fits `--max-width`, and
writes them as run-length-friendly row bitmaps with the colon centred on the
digit height.

    python clockdigits.py > ../../../src/activities/boot_sleep/ClockDigitFaces.h
"""

import argparse
import os

import freetype

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "..", "builtinFonts", "source", "Inter")
FACES = [
    ("CLOCK_DIGITS_SEMIBOLD", os.path.join(SOURCE, "Inter-SemiBold.woff")),
    ("CLOCK_DIGITS_LIGHT", os.path.join(SOURCE, "Inter-Light.woff")),
]
CHARS = "0123456789:-"

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--max-width", type=int, default=462, help="widest face in pixels (portrait X3 minus margins)")
args = parser.parse_args()


def render(face, ch):
    face.load_char(ch, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
    g = face.glyph
    bm = g.bitmap
    buf = bm.buffer
    rows = [[buf[y * bm.pitch + x] >= 128 for x in range(bm.width)] for y in range(bm.rows)]
    return {
        "width": bm.width,
        "height": bm.rows,
        "left": g.bitmap_left,
        "top": g.bitmap_top,  # baseline to bitmap top
        "advance": (g.advance.x + 32) >> 6,
        "rows": rows,
    }


def glyphs_at(path, px):
    face = freetype.Face(path)
    face.set_pixel_sizes(0, px)
    return {ch: render(face, ch) for ch in CHARS}


def widest_face(path, px):
    face = freetype.Face(path)
    face.set_pixel_sizes(0, px)

    def advance(ch):
        face.load_char(ch, freetype.FT_LOAD_DEFAULT)
        return (face.glyph.advance.x + 32) >> 6

    return 4 * max(advance(c) for c in "0123456789") + advance(":")


def pack(rows, width):
    out = bytearray()
    for row in rows:
        for x0 in range(0, width, 8):
            byte = 0
            for bit in range(8):
                x = x0 + bit
                if x < width and row[x]:
                    byte |= 0x80 >> bit
            out.append(byte)
    return out


print("// Generated by lib/EpdFont/scripts/clockdigits.py from Inter (SIL OFL 1.1). Do not edit.")
print("#pragma once")
print()
print("#include <cstdint>")
print()
print('#include "ClockDigits.h"')
print()

for name, path in FACES:
    px = 40
    while widest_face(path, px + 1) <= args.max_width:
        px += 1
    glyphs = glyphs_at(path, px)
    cap_top = max(glyphs[c]["top"] for c in "0123456789")
    cap_bottom = min(glyphs[c]["top"] - glyphs[c]["height"] for c in "0123456789")
    height = cap_top - cap_bottom

    bitmap = bytearray()
    entries = []
    for ch in CHARS:
        g = glyphs[ch]
        top = cap_top - g["top"]
        if ch == ":":
            top = (height - g["height"]) // 2
        entries.append((ch, g["width"], g["height"], g["advance"], g["left"], top, len(bitmap)))
        bitmap += pack(g["rows"], g["width"])

    print(f"// {os.path.basename(path)} at {px} px: digits {height} px tall, widest face {widest_face(path, px)} px")
    print(f"static constexpr uint8_t {name}_BITMAP[{len(bitmap)}] = {{")
    for i in range(0, len(bitmap), 24):
        print("    " + ", ".join(f"0x{b:02X}" for b in bitmap[i : i + 24]) + ",")
    print("};")
    print(f"static constexpr ClockDigitFace {name} = {{")
    print(f"    {height},")
    print(f"    {name}_BITMAP,")
    print("    {")
    for ch, w, h, adv, left, top, off in entries:
        print(f"        {{{w}, {h}, {adv}, {left}, {top}, {off}}},  // '{ch}'")
    print("    },")
    print("};")
    print()
